### ISSUE TITLE
Feature: task list

### ISSUE THREAD

**Issue by Maschette** [djnavarro/workbch#21]
Similar to the project list idea (#3) (which I assume would just list projects?) would be to have a todo_list() option where you can output the the task list for a project in a nice html format. 

You could use this internally for the project list function where project list uses the project title as the header of a tabset and calls task list to populate the tab.

It is hard with githubs auto formatting but something like: 
```
project_list(projects=c("project_1","project_11","project_42"), tabset=TRUE){
if(tabset){Title<-"#Project list: {.tabset}"} else(Title<-"#Project list: ")}
```
(' should be a back tick but github formats them)
'r Title'

.## 'r view_jobs(projects[1])$name'
'''{r}
todo_list(projects[1])
'''

which would output:

`#Project list: {.tabset}
## Project 1
alll of the things....
`

ok tabset doesn't for in issues but I think it makes sense....

**Comment by djnavarro** [comment]
I like this! I'll see what I can do :grin:

**Comment by Maschette** [comment]
It did occur to me that I was slightly more confused than I originally thought about the difference between a job and a project so I am not sure how it would work (or the package) across multiple projects?

**Comment by djnavarro** [comment]
Yeah, in my ideal world I'd have referred to "projects" everywhere instead of "jobs" (and that's how I wrote it initially), but I felt that would cause confusion with RStudio projects. So instead I've used "job" throughout (where one job could map onto one RStudio project or one git repo, or whatever), and allowed each job to be linked with a set of "tasks". However, there are still some stray references to "projects" in the documentation and the API (e.g., `goto_project()` should really be `goto_job()`) so right now it's really confusing.

**Comment by Maschette** [comment]
Ahh ok that clears it up in my head projects were projects and jobs were tasks.

**Comment by djnavarro** [comment]
Opened #24 as a reminder to fix the documentation on this

**Comment by djnavarro** [comment]
It needs some tidying, but here's the basic idea. There's a new function `view_site()` which I'll probably rename later, and it generates a tabbed HTML page as output. It has tabs for the task list, the job list, the table of known people and a details tab that allows you to click on and expand a job. Some screenshots below. Setting aside the fact that it's not very pretty right now, is this the sort of thing you were thinking of?

Here's the job list: 

![Screenshot from 2019-07-26 17-20-36](https://user-images.githubusercontent.com/2896325/61933922-67214900-afca-11e9-966a-b28c98e2bf53.png)

The expandable details tab (obviously needs nicer formatting):
 
![Screenshot from 2019-07-26 17-21-00](https://user-images.githubusercontent.com/2896325/61934019-aea7d500-afca-11e9-9b70-5a253851cc32.png)

The tasks view:

![Screenshot from 2019-07-26 17-21-20](https://user-images.githubusercontent.com/2896325/61934059-c3846880-afca-11e9-9928-26fb320438bd.png)

People tab:

![Screenshot from 2019-07-26 17-21-47](https://user-images.githubusercontent.com/2896325/61934075-d1d28480-afca-11e9-8eb5-bbd683919abb.png)
