### ISSUE TITLE
Bulk create jobs?

### ISSUE THREAD

**Issue by DataStrategist** [djnavarro/workbch#22]
So this is what I tried in order to create a ton of jobs in bulk such that I can use `git status` check.

```
 list.files(path = "..", full.names = TRUE) %>% discard(grepl("\\..{3,4}$", x =  ., perl = TRUE)) %>% map(~workbch::set_job(name = ., path = .))
```

> Error in if (!(owner %in% team)) { : argument is of length zero

So I'm listing all the files in the parent directory, throwing away files to keep only folders, and then mapping set_job where I'm setting the name to the path (cause I don't truly care too much), and the path as the path. It seems to think about it, but then throws the error quoted above.

Again, my use case is quite marginal so I'm totally down w/ it not being covered by your thingie, but if it is interesting to you, it's interesting to me!

Keep up the good work!

**Comment by djnavarro** [comment]
This isn't at all clean yet, but something like this should work. Suppose you want to initialise your workbch set up by having one job per git repo, where all git repos are subfolders of "my_projects". And just for the sake of argument let's suppose you want workbch to store its own files on the desktop. 

```
initialise_by_git(proj_dir = "my_projects", workbch_dir = "~/Desktop/")
```

This will auto-populate for you, setting "me" to be the owner of every project.  So from there this should work:
 
```
view_jobs()
view_git_status()
```

Let me know if it doesn't work. If it does, I'll spend a bit of time cleaning it up and making an analogous function that initialises using RStudio projects instead

**Comment by djnavarro** [comment]
The new `create_jobs_by_git` function should address this, as shown in the code snippet below. Suppose:

- you want workbch to store its own files at "~/Desktop/"
- you have many git repositories stored in "~/GitHub/"
- you want "Danielle" to be listed as the owner of created jobs

This should work (I hope)

```
set_home("~/Desktop/")
set_person("Danielle", "me")
create_jobs_by_git("~/GitHub/", owner = "me")
```

It should sweep through the "~/GitHub/" directory finding any ".git" folder; for each repo it finds it will ask you if you want to create a job based on that repo. Once that's done, you should have two new files on the desktop, "workbch_people.csv" and "workbch_jobs.json". At this point (hopefully!) commands like   `view_jobs()`, `view_git_status()` etc should work.

Please let me know if there are bugs (I haven't yet written unit tests for this)

**Comment by DataStrategist** [comment]
`create_jobs_by_git` worked perfectly... it did batch create jobs... however, unfortunately `view_git_status` didn't work immediately after:

```
view_git_status()
Error in git2r::ahead_behind(local = repo_head, upstream = upstream_head) : 
  Error in 'git2r_graph_ahead_behind': 'local' must be an S3 class git_commit
```
Just in case, I checked within the folder structure as well as `setwd()` outside of the github repos... just in case. No effect.

That said, `view_jobs()` does work. 

The implementation of setting the jobname of each job to increasing numbers of X isn't ideal as it's hard to then figure out what's what... it would arguably be better to parse each path to the name.... perhaps protecting terms by a quick `gsub("[^a-zA-Z]", "", x = path)` or so?

![image](https://user-images.githubusercontent.com/8094091/61717645-6635b080-ad59-11e9-9462-7f5b2b30021a.png)

What info can I get you?

**Comment by djnavarro** [comment]
Could you give me an example or two of what some of the paths to your git repos look like? The fact that those x's are showing up probably means my regex isn't parsing the paths properly on your machine and it's returning empty strings (and yes, fixing the "just add another x" silliness is definitely on the to-do list!)

**Comment by DataStrategist** [comment]
sure. Here's the first few lines of the jobs json file:

```

  "1": {
    "jobname": [""],
    "description": [""],
    "owner": ["Amit"],
    "status": ["active"],
    "team": ["Amit"],
    "priority": [1],
    "deadline": [null],
    "path": ["C:\\Users\\Amit\\Dropbox\\My projects\\ACDIVOCAdataGetter\\"],
    "urls": [
      {
        "site": "github",
        "link": "https://github.com/ACDIVOCATech/ACDIVOCAdataGetter/"
      },
      {
        "site": "github",
        "link": "git@gitlab.com:amit.kohli/ACDIVOCAdataGetter/"
      }
    ],
    "tasks": [],
    "notes": [],
    "hidden": [false]
  },
  "X": {
    "jobname": ["X"],
    "description": ["X"],
    "owner": ["Amit"],
    "status": ["active"],
    "team": ["Amit"],
    "priority": [1],
    "deadline": [null],
    "path": ["C:\\Users\\Amit\\Dropbox\\My projects\\Amit & Laure - 1 yr\\"],
    "urls": [],
    "tasks": [],
    "notes": [],
    "hidden": [false]
  },
  "XX": {
    "jobname": ["XX"],
    "description": ["XX"],
    "owner": ["Amit"],
    "status": ["active"],
    "team": ["Amit"],
    "priority": [1],
    "deadline": [null],
    "path": ["C:\\Users\\Amit\\Dropbox\\My projects\\amitkohli.com\\"],
    "urls": [
      {
        "site": "github",
        "link": "https://github.com/DataStrategist/amitkohli.com/"
      }
    ],
    "tasks": [],
    "notes": [],
    "hidden": [false]
  },
  "XXX": {
    "jobname": ["XXX"],
    "description": ["XXX"],
    "owner": ["Amit"],
    "status": ["active"],
    "team": ["Amit"],
    "priority": [1],
    "deadline": [null],
    "path": ["C:\\Users\\Amit\\Dropbox\\My projects\\AQUASTAT - AQUASTAT package\\"],
    "urls": [],
    "tasks": [],
    "notes": [],
    "hidden": [false]
  }

```

Remind me to delete this after we're done debugging!

**Comment by djnavarro** [comment]
Thanks! Pretty sure the problem is that my regex isn't handling Windows file paths properly. I'll look at it tomorrow. Feel free to delete (I have a copy, which I'll delete as soon as the bugfix is done)

**Comment by djnavarro** [comment]
I _think_ the current version should work properly? It seems to work on my Windows machine as well as my Ubuntu machine. Would you mind seeing if it works for you now?

**Comment by djnavarro** [comment]
There's still an issue with it not properly supporting anything other than GitHub (so it does weird things for GitLab, Bitbucket etc) but I'll open a separate issue for that

**Comment by djnavarro** [comment]
FYI the function has subsequently been renamed `make_jobs_by_git` to avoid overlap with usethis

**Comment by DataStrategist** [comment]
Hi... I think there's something funky w/ latest version. I uninstalled and reinstalled using `remotes::install_github` but the function for `make_jobs_by_git` still doesn't show up, while I still seem to have the `create_....`. Could you rebuild the package and perhaps `roxygenize()` again? 

Also, to be clear, the json with jobs WAS successfuly created... the problem I had was with `view_git_status`

**Comment by djnavarro** [comment]
Hm. This is odd. I've tried rebuilding, rerunning roxygenise etc, and nothing changes: everything appears to be up to date. I've tried reinstalling myself using 

```
remotes::install_github("djnavarro/workbch")
```

and everything works fine. I'm not sure why the function doesn't appear for you.

One suggestion I have is that we try to separate the issue with `view_git_status()` from the issue with `make_jobs_by_git()`. My original thought was that there was something weird going on with how `make_jobs_by_git()` was creating the jobs file. That was was definitely true, and I had thought I'd fixed it (but maybe not!)

What I was going to suggest -- assuming you can get the current version to install -- is that you try the following process:

1. delete the workbch_jobs.json file and the workbch_people.csv file
2. create a few jobs manually with `make_job()`
3. see if you can reproduce the `view_git_status()` error

If you can produce the error that way, we can at least be more certain there's a problem with `view_git_status()` itself.
